apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rancher.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ .Values.rancher.url | b64enc }}
  token: {{ .Values.rancher.token | b64enc }}
  srImageRepository: {{ .Values.rancher.srImageRepository | b64enc }}
  s3Endpoint: {{ .Values.s3.endpoint | b64enc }}
  s3Region: {{ .Values.s3.region | b64enc }}
  s3Bucket: {{ .Values.s3.bucket | b64enc }}
  s3Folder: {{ .Values.s3.folder | b64enc }}
  s3InsecureTLSSkipVerify: {{ .Values.s3.insecureTLSSkipVerify | quote | b64enc }}
  s3AccessKeyId: {{ .Values.s3.accessKeyId | b64enc }}
  s3SecretAccessKey: {{ .Values.s3.secretAccessKey | b64enc }}
